### ISSUE TITLE
 Warning: Each child in a list should have a unique "key" prop. when i run inference in the browser.

### ISSUE THREAD

**Issue by KudzayiKing** [IBM/tfjs-web-app#17]
HI! I made a plant leaf diseases classification using _transfer learning_ **MobileNet**, i saved my model as **h5** the converted it into **.js**, in the app i changed **classes.js** to fit the SoftMax of my model which was 38 classes, When I run the app it does not show the classes , it jus shows the probabilities , but interestingly when i put classes.js with **ImageNet** classes , classes appear in app .where a I going wrong ? I have attaches files below . @pvaneck @xgqfrms @autumnblue @joshpitzalis @jdhiro @keithort @Diaver

![app error 1](https://user-images.githubusercontent.com/66751252/102024808-4c10ce00-3da5-11eb-9ced-c9860b5b0903.jpg)
![app error 2](https://user-images.githubusercontent.com/66751252/102024814-5337dc00-3da5-11eb-95b4-8883ea586c03.jpg)
**classify.js**
`const MODEL_PATH = '/model/model.json';
const IMAGE_SIZE = 224;
const CANVAS_SIZE = 224;
const TOPK_PREDICTIONS = 5;

const INDEXEDDB_DB = 'tensorflowjs';
const INDEXEDDB_STORE = 'model_info_store';
const INDEXEDDB_KEY = 'web-model';

/**
 * Class to handle the rendering of the Classify page.
 * @extends React.Component
 */
export default class Classify extends Component {

  constructor(props) {
    super(props);

    this.webcam = null;
    this.model = null;
    this.modelLastUpdated = null;

    this.state = {
      modelLoaded: false,
      filename: '',
      isModelLoading: false,
      isClassifying: false,
      predictions: [],
      photoSettingsOpen: true,
      modelUpdateAvailable: false,
      showModelUpdateAlert: false,
      showModelUpdateSuccess: false,
      isDownloadingModel: false
    };
  }

  async componentDidMount() {
    if (('indexedDB' in window)) {
      try {
        this.model = await tf.loadLayersModel('indexeddb://' + INDEXEDDB_KEY);

        // Safe to assume tensorflowjs database and related object store exists.
        // Get the date when the model was saved.
        try {
          const db = await openDB(INDEXEDDB_DB, 1, );
          const item = await db.transaction(INDEXEDDB_STORE)
                               .objectStore(INDEXEDDB_STORE)
                               .get(INDEXEDDB_KEY);
          const dateSaved = new Date(item.modelArtifactsInfo.dateSaved);
          await this.getModelInfo();
          console.log(this.modelLastUpdated);
          if (!this.modelLastUpdated  || dateSaved >= new Date(this.modelLastUpdated).getTime()) {
            console.log('Using saved model');
          }
          else {
            this.setState({
              modelUpdateAvailable: true,
              showModelUpdateAlert: true,
            });
          }

        }
        catch (error) {
          console.warn(error);
          console.warn('Could not retrieve when model was saved.');
        }

      }
      // If error here, assume that the object store doesn't exist and the model currently isn't
      // saved in IndexedDB.
      catch (error) {
        console.log('Not found in IndexedDB. Loading and saving...');
        console.log(error);
        this.model = await tf.loadLayersModel(MODEL_PATH);
        await this.model.save('indexeddb://' + INDEXEDDB_KEY);
      }
    }
    // If no IndexedDB, then just download like normal.
    else {
      console.warn('IndexedDB not supported.');
      this.model = await tf.loadLayersModel(MODEL_PATH);
    }

    this.setState({ modelLoaded: true });
    this.initWebcam();

    // Warm up model.
    let prediction = tf.tidy(() => this.model.predict(tf.zeros([1, IMAGE_SIZE, IMAGE_SIZE, 3])));
    prediction.dispose();
  }

  async componentWillUnmount() {
    if (this.webcam) {
      this.webcam.stop();
    }

    // Attempt to dispose of the model.
    try {
      this.model.dispose();
    }
    catch (e) {
      // Assume model is not loaded or already disposed.
    }
  }

  initWebcam = async () => {
    try {
      this.webcam = await tf.data.webcam(
        this.refs.webcam,
        {resizeWidth: CANVAS_SIZE, resizeHeight: CANVAS_SIZE, facingMode: 'environment'}
      );
    }
    catch (e) {
      this.refs.noWebcam.style.display = 'block';
    }
  }

  startWebcam = async () => {
    if (this.webcam) {
      this.webcam.start();
    }
  }

  stopWebcam = async () => {
    if (this.webcam) {
      this.webcam.stop();
    }
  }

  getModelInfo = async () => {
    await fetch(`${config.API_ENDPOINT}/model_info`, {
      method: 'GET',
    })
    .then(async (response) => {
      await response.json().then((data) => {
        this.modelLastUpdated = data.last_updated;
      })
      .catch((err) => {
        console.log('Unable to get parse model info.');
      });
    })
    .catch((err) => {
      console.log('Unable to get model info');
    });
  }

  updateModel = async () => {
    // Get the latest model from the server and refresh the one saved in IndexedDB.
    console.log('Updating the model: ' + INDEXEDDB_KEY);
    this.setState({ isDownloadingModel: true });
    this.model = await tf.loadLayersModel(MODEL_PATH);
    await this.model.save('indexeddb://' + INDEXEDDB_KEY);
    this.setState({
      isDownloadingModel: false,
      modelUpdateAvailable: false,
      showModelUpdateAlert: false,
      showModelUpdateSuccess: true
    });
  }

  classifyLocalImage = async () => {
    this.setState({ isClassifying: true });

    const croppedCanvas = this.refs.cropper.getCroppedCanvas();
    const image = tf.tidy( () => tf.browser.fromPixels(croppedCanvas).toFloat());

    // Process and resize image before passing in to model.
    const imageData = await this.processImage(image);
    const resizedImage = tf.image.resizeBilinear(imageData, [IMAGE_SIZE, IMAGE_SIZE]);

    const logits = this.model.predict(resizedImage);
    const probabilities = await logits.data();
    const preds = await this.getTopKClasses(probabilities, TOPK_PREDICTIONS);

    this.setState({
      predictions: preds,
      isClassifying: false,
      photoSettingsOpen: !this.state.photoSettingsOpen
    });

    // Draw thumbnail to UI.
    const context = this.refs.canvas.getContext('2d');
    const ratioX = CANVAS_SIZE / croppedCanvas.width;
    const ratioY = CANVAS_SIZE / croppedCanvas.height;
    const ratio = Math.min(ratioX, ratioY);
    context.clearRect(0, 0, CANVAS_SIZE, CANVAS_SIZE);
    context.drawImage(croppedCanvas, 0, 0,
                      croppedCanvas.width * ratio, croppedCanvas.height * ratio);

    // Dispose of tensors we are finished with.
    image.dispose();
    imageData.dispose();
    resizedImage.dispose();
    logits.dispose();
  }

  classifyWebcamImage = async () => {
    this.setState({ isClassifying: true });

    const imageCapture = await this.webcam.capture();

    const resized = tf.image.resizeBilinear(imageCapture, [IMAGE_SIZE, IMAGE_SIZE]);
    const imageData = await this.processImage(resized);
    const logits = this.model.predict(imageData);
    const probabilities = await logits.data();
    const preds = await this.getTopKClasses(probabilities, TOPK_PREDICTIONS);

    this.setState({
      predictions: preds,
      isClassifying: false,
      photoSettingsOpen: !this.state.photoSettingsOpen
    });

    // Draw thumbnail to UI.
    const tensorData = tf.tidy(() => imageCapture.toFloat().div(255));
    await tf.browser.toPixels(tensorData, this.refs.canvas);

    // Dispose of tensors we are finished with.
    resized.dispose();
    imageCapture.dispose();
    imageData.dispose();
    logits.dispose();
    tensorData.dispose();
  }

  processImage = async (image) => {
    return tf.tidy(() => image.expandDims(0).toFloat().div(127).sub(1));
  }

  /**
   * Computes the probabilities of the topK classes given logits by computing
   * softmax to get probabilities and then sorting the probabilities.
   * @param logits Tensor representing the logits from MobileNet.
   * @param topK The number of top predictions to show.
   */
  getTopKClasses = async (values, topK) => {
    const valuesAndIndices = [];
    for (let i = 0; i < values.length; i++) {
      valuesAndIndices.push({value: values[i], index: i});
    }
    valuesAndIndices.sort((a, b) => {
      return b.value - a.value;
    });
    const topkValues = new Float32Array(topK);
    const topkIndices = new Int32Array(topK);
    for (let i = 0; i < topK; i++) {
      topkValues[i] = valuesAndIndices[i].value;
      topkIndices[i] = valuesAndIndices[i].index;
    }

    const topClassesAndProbs = [];
    for (let i = 0; i < topkIndices.length; i++) {
      topClassesAndProbs.push({
        className: MODEL_CLASSES[topkIndices[i]],
        probability: (topkValues[i] * 100).toFixed(2)
      });
    }
    return topClassesAndProbs;
  }

  handlePanelClick = event => {
    this.setState({ photoSettingsOpen: !this.state.photoSettingsOpen });
  }

  handleFileChange = event => {
    if (event.target.files && event.target.files.length > 0) {
      this.setState({
        file: URL.createObjectURL(event.target.files[0]),
        filename: event.target.files[0].name
      });
    }
  }

  handleTabSelect = activeKey => {
    switch(activeKey) {
      case 'camera':
        this.startWebcam();
        break;
      case 'localfile':
        this.setState({filename: null, file: null});
        this.stopWebcam();
        break;
      default:
    }
  }

  render() {
    return (
      <div className="Classify container">

      { !this.state.modelLoaded &&
        <Fragment>
          <Spinner animation="border" role="status">
            <span className="sr-only">Loading...</span>
          </Spinner>
          {' '}<span className="loading-model-text">Loading Model</span>
        </Fragment>
      }

      { this.state.modelLoaded &&
        <Fragment>
        <Button
          onClick={this.handlePanelClick}
          className="classify-panel-header"
          aria-controls="photo-selection-pane"
          aria-expanded={this.state.photoSettingsOpen}
          >
          Take or Select a Photo to Classify
            <span className='panel-arrow'>
            { this.state.photoSettingsOpen
              ? <FaChevronDown />
              : <FaChevronRight />
            }
            </span>
          </Button>
          <Collapse in={this.state.photoSettingsOpen}>
            <div id="photo-selection-pane">
            { this.state.modelUpdateAvailable && this.state.showModelUpdateAlert &&
                <Container>
                  <Alert
                    variant="info"
                    show={this.state.modelUpdateAvailable && this.state.showModelUpdateAlert}
                    onClose={() => this.setState({ showModelUpdateAlert: false})}
                    dismissible>
                      An update for the <strong>{this.state.modelType}</strong> model is available.
                      <div className="d-flex justify-content-center pt-1">
                        {!this.state.isDownloadingModel &&
                          <Button onClick={this.updateModel}
                                  variant="outline-info">
                            Update
                          </Button>
                        }
                        {this.state.isDownloadingModel &&
                          <div>
                            <Spinner animation="border" role="status" size="sm">
                              <span className="sr-only">Downloading...</span>
                            </Spinner>
                            {' '}<strong>Downloading...</strong>
                          </div>
                        }
                      </div>
                  </Alert>
                </Container>
              }
              {this.state.showModelUpdateSuccess &&
                <Container>
                  <Alert variant="success"
                         onClose={() => this.setState({ showModelUpdateSuccess: false})}
                         dismissible>
                    The <strong>{this.state.modelType}</strong> model has been updated!
                  </Alert>
                </Container>
              }
            <Tabs defaultActiveKey="camera" id="input-options" onSelect={this.handleTabSelect}
                  className="justify-content-center">
              <Tab eventKey="camera" title="Take Photo">
                <div id="no-webcam" ref="noWebcam">
                  <span className="camera-icon"><FaCamera /></span>
                  No camera found. <br />
                  Please use a device with a camera, or upload an image instead.
                </div>
                <div className="webcam-box-outer">
                  <div className="webcam-box-inner">
                    <video ref="webcam" autoPlay playsInline muted id="webcam"
                           width="448" height="448">
                    </video>
                  </div>
                </div>
                <div className="button-container">
                  <LoadButton
                    variant="primary"
                    size="lg"
                    onClick={this.classifyWebcamImage}
                    isLoading={this.state.isClassifying}
                    text="Classify"
                    loadingText="Classifying..."
                  />
                </div>
              </Tab>
              <Tab eventKey="localfile" title="Select Local File">
                <Form.Group controlId="file">
                  <Form.Label>Select Image File</Form.Label><br />
                  <Form.Label className="imagelabel">
                    {this.state.filename ? this.state.filename : 'Browse...'}
                  </Form.Label>
                  <Form.Control
                    onChange={this.handleFileChange}
                    type="file"
                    accept="image/*"
                    className="imagefile" />
                </Form.Group>
                { this.state.file &&
                  <Fragment>
                    <div id="local-image">
                      <Cropper
                        ref="cropper"
                        src={this.state.file}
                        style={{height: 400, width: '100%'}}
                        guides={true}
                        aspectRatio={1 / 1}
                        viewMode={2}
                      />
                    </div>
                    <div className="button-container">
                      <LoadButton
                        variant="primary"
                        size="lg"
                        disabled={!this.state.filename}
                        onClick={this.classifyLocalImage}
                        isLoading={this.state.isClassifying}
                        text="Classify"
                        loadingText="Classifying..."
                      />
                    </div>
                  </Fragment>
                }
              </Tab>
            </Tabs>
            </div>
          </Collapse>
          { this.state.predictions.length > 0 &&
            <div className="classification-results">
              <h3>Predictions</h3>
              <canvas ref="canvas" width={CANVAS_SIZE} height={CANVAS_SIZE} />
              <br />
              <ListGroup>
              {this.state.predictions.map((category) => {
                  return (
                    <ListGroup.Item key={category.className}>
                      <strong>{category.className}</strong> {category.probability}%</ListGroup.Item>
                  );
              })}
              </ListGroup>
            </div>
          }
          </Fragment>
        }
      </div>
    );
  }
}`

**classes.js**
`/* eslint-disable */
// Theses classes should correspond to the softmax output of your model.

export const MODEL_CLASSES = {
  0: 'Apple___Apple_scab',
  1: 'Apple___Black_rot', 
  2: 'Apple___Cedar_apple_rust', 
  3: 'Apple___healthy',
  4: 'Blueberry___healthy', 
  5: 'Cherry_(including_sour)___Powdery_mildew', 
  6: 'Cherry_(including_sour)___healthy', 
  7: 'Corn_(maize)___Cercospora_leaf_spot Gray_leaf_spot',
  8: 'Corn_(maize)___Common_rust', 
  9: 'Corn_(maize)___Northern_Leaf_Blight', 
  10: 'Corn_(maize)___healthy', 
  11: 'Grape___Black_rot', 
  12: 'Grape___Esca_(Black_Measles)', 
  13: 'Grape___Leaf_blight_(Isariopsis_Leaf_Spot)', 
  14: 'Grape___healthy', 
  15: 'Orange___Haunglongbing_(Citrus_greening)', 
  16: 'Peach___Bacterial_spot', 
  17: 'Peach___healthy', 
  18: 'Pepper,_bell___Bacterial_spot', 
  19: 'Pepper,_bell___healthy', 
  20: 'Potato___Early_blight', 
  21: 'Potato___Late_blight', 
  22: 'Potato___healthy', 
  23: 'Raspberry___healthy', 
  24: 'Soybean___healthy', 
  25: 'Squash___Powdery_mildew', 
  26: 'Strawberry___Leaf_scorch', 
  27: 'Strawberry___healthy', 
  28: 'Tomato___Bacterial_spot', 
  29: 'Tomato___Early_blight', 
  30: 'Tomato___Late_blight', 
  31: 'Tomato___Leaf_Mold', 
  32: 'Tomato___Septoria_leaf_spot', 
  33: 'Tomato___Spider_mites Two-spotted_spider_mite', 
  34: 'Tomato___Target_Spot', 
  35: 'Tomato___Tomato_Yellow_Leaf_Curl_Virus', 
  36: 'Tomato___Tomato_mosaic_virus', 
  37: 'Tomato___healthy'
};
`

**Comment by pvaneck** [comment]
In the `getTopKClasses` function, can you do add a `console.log(values.length);`? The error you see typically indicates that the class that corresponds to the index is undefined. This generally happens when there is a mismatch between the lengths of the output softmax array and the number of possible classes. So, the value you should see for `console.log(values.length);` should be 38 assuming the app is loading the correct model and the model was trained properly so that the output shape is 38.

**Comment by KudzayiKing** [comment]
@pvaneck Thank you for the quick reply, the console shows `1000`

**Comment by pvaneck** [comment]
Sounds like you are still using the original MobileNet model since the model  prediction output is giving you 1000 class probabilities. Double check to make sure that the updated model files are in the `public/model` directory. Might also be worthwhile to double check the output of your Keras model in python to ensure that the output size is 38.

**Comment by KudzayiKing** [comment]
@pvaneck I ran `model.summary()` on the `model.h5`  , `output is 38` , and yes I updated the files in `public/model` and `scr/public/model/classes.js`. I also saved one version of the model with `ImageDataGeneration` `class_mode="categorical"`  with `loss="CategoricalCrossentropy"` and another one with `class_mode="sparse"`  with `loss="SparseCategoricalCrossentropy"` nothing changed both versions did not show classes.


![app error 4](https://user-images.githubusercontent.com/66751252/102158882-78a31380-3e93-11eb-8e4f-2ebf602e3946.jpg)

**Comment by KudzayiKing** [comment]
@pvaneck  another thing i noticed is at `{this.state.predictions.map((category) => { console.log('category:', category)` shows this in the console 
![app error 5](https://user-images.githubusercontent.com/66751252/102161034-9ffbdf80-3e97-11eb-9e11-7ddbb812dceb.jpg)

**Comment by pvaneck** [comment]
Can you also do a `this.model.summary()` somewhere and see what the output shape is? Can just put it near where you put `console.log(values.length);`. If the model is correct and was converted properly, output shape should be `[null, 38]`. A shape of `[null, 1000]` seems the indicate the original Mobilenet with the 1000 ImageNet classes are being used.

**Comment by KudzayiKing** [comment]
@pvaneck Yes your suspicions are right ! it shows `[null,1000]` in the console. Guess i need to get back to saving the Model .Is this caused by `tfjs-converter` or i need to specifically save the model with `specifying signatures during export` https://www.tensorflow.org/guide/saved_model#specifying_signatures_during_export
![MODEL OUTPUT](https://user-images.githubusercontent.com/66751252/102262010-8b652900-3f23-11eb-9e8c-4da4b579c7a3.jpg)

**Comment by pvaneck** [comment]
You were exporting your model in the h5 format, right? Those signatures just apply to the TF SavedModel format. Converting an h5 file is outlined here: https://www.tensorflow.org/js/tutorials/conversion/import_keras (just make sure you use the correct plant leaf model when converting via `tensorflowjs_converter --input_format=keras ./path/to/plant-leaf-model.h5 ./my-model`.

**Comment by KudzayiKing** [comment]
@pvaneck yes I am exporting `h5` the converting it to `.js` directly using `tfjs.converters.save_keras_model(model, tfjs_target_dir)` and i am also saving the `h5` the converting it to `.js` somewhere else . I have uploaded the `h5` file to cross check output shape what i am getting is `[null,38]`
![MODEL OUTPUT 2](https://user-images.githubusercontent.com/66751252/102327720-34993700-3f97-11eb-8022-f67d3d4fec78.jpg)

And this is the `h5` I have converted and put in my `public/model`. Console still shows `[null,1000]` after running `Classify`
![console output](https://user-images.githubusercontent.com/66751252/102328037-99ed2800-3f97-11eb-9b29-a4696f5a2c38.jpg)

So I can't understand were things are going wrong .

**Comment by KudzayiKing** [comment]
@pvaneck  I was just going through some images testing , a couple images actually have their classes appearing in the app , as in picture below. Why am I getting the feeling that the `converter` is not converting the model properly .Maybe I should use a previous version of the converter ?
![console output4](https://user-images.githubusercontent.com/66751252/102331771-4c26ee80-3f9c-11eb-8193-e1d643e4211f.jpg)

**Comment by pvaneck** [comment]
Can you show the python code that constructs and saves your h5 model? That model.summary in the console only looks like the base mobilenet model layers.

I tried reconstructing a model similar to yours:

```
base_model = tf.keras.applications.MobileNet(
    input_shape=(224, 224, 3),
    include_top=False, weights='imagenet',
    classifier_activation='softmax'
)
base_model.trainable = False
input_1 = tf.keras.layers.Input(shape=(224,224,3))
x = base_model(input_1)
x = tf.keras.layers.GlobalAveragePooling2D()(x)
x = tf.keras.layers.Dropout(0)(x)
x = tf.keras.layers.Dense(38, activation='softmax')(x)

model = tf.keras.models.Model(inputs=input_1, outputs=x)
model.summary()
tfjs.converters.save_keras_model(model, './tfjs-output')
```
This gives a model summary just like yours:
```
Model: "model"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
=================================================================
input_2 (InputLayer)         [(None, 224, 224, 3)]     0         
_________________________________________________________________
mobilenet_1.00_224 (Function (None, 7, 7, 1024)        3228864   
_________________________________________________________________
global_average_pooling2d (Gl (None, 1024)              0         
_________________________________________________________________
dropout (Dropout)            (None, 1024)              0         
_________________________________________________________________
dense (Dense)                (None, 38)                38950     
=================================================================
Total params: 3,267,814
Trainable params: 38,950
Non-trainable params: 3,228,864
```
The converted model loaded in tensorflow looks to be the same as expected:
```
_________________________________________________________________
tfjs@2.4.0:17 Layer (type)                 Output shape              Param #   
tfjs@2.4.0:17 =================================================================
tfjs@2.4.0:17 input_2 (InputLayer)         [null,224,224,3]          0         
tfjs@2.4.0:17 _________________________________________________________________
tfjs@2.4.0:17 mobilenet_1.00_224 (Function [null,7,7,1024]           3228864   
tfjs@2.4.0:17 _________________________________________________________________
tfjs@2.4.0:17 global_average_pooling2d (Gl [null,1024]               0         
tfjs@2.4.0:17 _________________________________________________________________
tfjs@2.4.0:17 dropout (Dropout)            [null,1024]               0         
tfjs@2.4.0:17 _________________________________________________________________
tfjs@2.4.0:17 dense (Dense)                [null,38]                 38950     
tfjs@2.4.0:17 =================================================================
tfjs@2.4.0:17 Total params: 3267814
tfjs@2.4.0:17 Trainable params: 38950
tfjs@2.4.0:17 Non-trainable params: 3228864
tfjs@2.4.0:17 _________________________________________________________________
```
So, I would double check your model saving to ensure you are not just saving the base model.

Sidenote: In trying this, seems like we need a minimum TF version of 2.4.0 (for Functional layer support) but also a version less than 2.8.0 (just released and it seems to introduce a bug that breaks the webcam component of the app). So I will probably submit a PR updating the package.json.

My tests were with tensorflowjs==2.8.0 (Python) and @tensorflow/tfjs==2.7.0 (JavaScript).

**Comment by KudzayiKing** [comment]
@pvaneck Thanks  , here is the full [PYTHON CODE](https://www.kaggle.com/kudzayiking/leaf-disease-classification-mobilenet-94) take a look , while I cross check the versions !let me know if there are any errors in the `python` code !

**Comment by pvaneck** [comment]
@KudzayiKing The code seems to look fine and should export a working model. Hmm, now that I think about it, perhaps the app keeps using an old model your previously loaded and is not picking up any updated models you put in `public/model`. By default the app will keep fetching a saved model in IndexedDB in the browser (giving it offline functionality). To force the app to load the latest model, either update `model_info.txt` with a newer date (`date > model_info.txt`) or you can just  delete the indexeddb tensorflowjs database in the browser. Reloading should then pull in the new model.

![image](https://user-images.githubusercontent.com/1868861/102427382-11d24700-3fc6-11eb-831d-1715432c6b92.png)

**Comment by KudzayiKing** [comment]
@pvaneck Yes it worked !everything is now working well ! I just deleted the `tensorflowjs database ` .Thanks for the support. Please check your email!
